# Generated by Django 5.1.3 on 2024-11-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Rent", "Rent"),
                            ("Groceries", "Groceries"),
                            ("Transportation", "Transportation"),
                            ("Entertainment", "Entertainment"),
                            ("Miscellaneous", "Miscellaneous"),
                            ("Food", "Food"),
                        ],
                        max_length=120,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
            ],
        ),
    ]
